version: "3.7"

services:
  redis:
    #image: redislabs/redisearch:2.8.8
    image: redis/redis-stack:7.4.0-v0-x86_64
    ports:
      - '6379:6379'
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 25Gb
